### ISSUE TITLE
Download extension doesn't contain any templates

### ISSUE THREAD

**Issue by PatrickWynne** [Burgyn/Angular2VisualStudioTemplate#1]
I finished the installation I thought, but when I go to select this template I receive an error message.

"Download extension doesn't contain any templates"

**Comment by Burgyn** [comment]
Hi,
thanks for report.
But I can't reproduce it.
Please can you give me more aditional information?

For example:
 - Visual Studio version?
 - How did you installed this template? By visual studio or directly downloading from web?
 - any screenshot?
 - is anything suspects in visual studio ActivityLog?

Thanks.

**Comment by Interkodex** [comment]
Visual Studio 2017 with Update 1 (or what it is called)

![image](https://cloud.githubusercontent.com/assets/22881643/24619669/145f6fb2-189b-11e7-9a50-d6f94d3137a9.png)

![image](https://cloud.githubusercontent.com/assets/22881643/24619575/b4b9e3e4-189a-11e7-90a0-31eac31eed9c.png)

Microsoft Visual Studio Professional 2017
Version 15.0.26228.10 D15RTWSVC
Microsoft .NET Framework
Version 4.6.01586

Installed Version: Professional

Visual Basic 2017   00370-10250-02356-AA719
Microsoft Visual Basic 2017

Visual C# 2017   00370-10250-02356-AA719
Microsoft Visual C# 2017

Application Insights Tools for Visual Studio Package   8.6.00209.10
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.30223.0
ASP.NET and Web Tools 2017

ASP.NET Web Frameworks and Tools 2017   5.2.50127.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.30209.0
Azure App Service Tools v3.0.0

Common Azure Tools   1.9
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

KofePackagePackage Extension   1.0
KofePackagePackage Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.50131.1

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Node.js Tools   1.3.50201.08
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   4.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

SQL Server Data Tools   15.1.61702.140
Microsoft SQL Server Data Tools

TypeScript   2.1.5.0
TypeScript tools for Visual Studio

Not familiar on using the "ActivityLog" in VS2017? Is it approach something like this: https://blogs.msdn.microsoft.com/visualstudio/2010/02/24/troubleshooting-extensions-with-the-activity-log/ ?

**Comment by Burgyn** [comment]
Hi,
thanks for aditional information.

Please can you try it from **installed section** not from online?
![image](https://cloud.githubusercontent.com/assets/5930822/24642716/a0390606-1909-11e7-8ad8-b012290079d1.png)

**Comment by Interkodex** [comment]
Great that worked, thanks! I couldn't find it the other day, I was looking under "Web", never used templates before and didn't know they were hidden down there. Nice and clean template, just what I was looking for - thanks a bunch!

**Comment by Burgyn** [comment]
I'm glad I helped you.

Please, can you give me review on [marketplace](https://marketplace.visualstudio.com/items?itemName=Mino.Angular2VisualStudioTemplate)? 

Thanks.

**Comment by Interkodex** [comment]
Absolutely, I actually already wrote it! 👍  🥇
