### ISSUE TITLE
Feature - Include Webpack build process to help productivity.

### ISSUE THREAD

**Issue by Jamie-Clayton** [Burgyn/Angular2VisualStudioTemplate#4]
The developer workflow when using this template could be improved. Angular html/css/ts file changes requires constant rebuilding of solution to display those changes which slows down the engineering process.

I've worked with one of the .net core spa angular templates which use a combination of MVC + angular.  One of the nice approaches by that template is the use of the Webpack middleware pipeline that allows you to make changes to your angular components and then webpack automatically hot swaps those changes to the web browser with out the need to stop, recompile and then run the VS 2017 debugger again.  

It would be good if this pure angular project could include that more advanced "Webpack" build process to help improve developer productivity as well as prepare the solution for "Production" deployment by the optimization of the various assets required for an efficient web site with Angular.

Webpack is a PITA to setup and configure, but once it's going the benefits are well worth the effort IMHO.

**Comment by Burgyn** [comment]
Hi, 
thanks for your good suggestion.

The benefits are obvious.
Unfortunately actualy I'm bussy.
If you know how and if you fancy, you can help me. This project is open source.

Thanks.

**Comment by Jamie-Clayton** [comment]
Sorry, this comment is a little dated. I'll close for now and determine if this is valid in 2024.
